const listInv = ["GINA FUENZALIDA", "FERNANDO CÁCERES", "MARIA JOSÉ CÁCERES", "SEGISFREDO VERDEJO", "CARMEN ALVAREZ", 
"MILDRED VERDEJO", "OCTAVIO VERDEJO", "JEANNETTE DOMÍNGUEZ", "ELISA QUEZADA", "YELITZA FUENZALIDA", "LUIS VERDEJO",
"PATRICIA MOLINA", "PATRICIA MORALES", "CARLOS CORREA", "PÍA CORREA", "VIVIANA PINO", "JOSÉ OLIVARES", "RICARDO LUZA",
"FABIOLA RODRIGUEZ", "FLAVIO NARRIA", "FANNY PIZARRO", "MARIANO GARCÍA", "MARITZA PIZARRO", " PETER ROSENTHAL",
"DARWIN PIZARRO", "MIRNA RIOS", "CARLOS LUZA", "SLVIA LUNA", "GERARDO CAROCA", "GABRIELA VIVANCO", "NICOLÁS LUZA"]

const checkInvitados = (name) =>{
    return listInv.includes(name.toUpperCase())
}

module.exports = checkInvitados